# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: ynov-devops-tp2-team-5
      DOCKERHUB_USERNAME: kaunogan
      DOCKERHUB_PASS: 647D22C45C

    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  launch-project:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.13.0

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .circleci/node/
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  build-image:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker # Ask circleci new Docker Engine to build outside of container
      - run:
          name: View working directory tree
          command: ls -lahR
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .circleci/node/
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-master:
    jobs:
      - launch-project:
          filters:
            branches:
              only: master
      - build-image:
          requires:
            - launch-project
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build-image
          filters:
            branches:
              only: master